homepage:
  headline: "Kathleen Reyes"
  byline: "Designer + Illustrator + Cat Fan 😻"

about:
  headline: "Oh, heyyy!"
  text: "I’m Kathleen or Kath (she/her), a latina designer and illustrator living in extra sunny Orlando, FL, US. A fan of simple and joyful design with a background in print production, branding, and communication. My design concentrations are brand development and marketing. My illustration work is empowering, positive, and playful."

contact:
  headline: "Wanna collaborate?"
  link-text: "Let's do it!"
  link-url: "katreyyy@gmail.com"

four-o-four:
  headline: "Ooops, where ya going? (404)"
  link-text: "Take me back home!"
  link-url: "/"

socials:
  instagram: "https://www.instagram.com/katreyyy/"
  dribbble: "https://dribbble.com/katreyyy"
  behance: "https://www.behance.net/katreyyy"