homepage:
  headline: Kathleen Reyes
  byline: Designer + Illustrator
about:
  headline: Hola!
  text: I’m Kath Reyes (she/her), a latina designer and illustrator living in
    sometimes-sunny-sometimes-rainy Orlando, FL, U.S. I enjoy working on simple
    and joyful design that focuses on people, storytelling, and community. My
    illustration work is empowering, positive, and playful.
contact:
  headline: Wanna collaborate?
  link-text: Let's talk!
  link-url: katreyyy@gmail.com
four-o-four:
  headline: Oops, where ya going? (404)
  link-text: Let's go back.
  link-url: /
socials:
  instagram: https://www.instagram.com/katreyyy/
  instagram-alt: Instagram icon.
  dribbble: https://dribbble.com/katreyyy
  dribbble-alt: Dribbble icon.
  behance: https://www.behance.net/katreyyy
  behance-alt: Behance icon.
