backend:
  name: github
  repo: dlvjose/katreyyy 

publish_mode: editorial_workflow
  
media_folder: "assets/images/uploads"

collections:
  - name: "site-settings"
    label: "Site Settings"
    files:
      - label: "Site Settings"
        name: "site"
        file: "_data/site.yml"
        fields: 
          - label: "Social Accounts"
            name: "socials"
            widget: "object"
            fields:
            - label: "Instagram"
              name: "instagram"
              widget: "string"
            - label: "Dribbble"
              name: "dribbble"
              widget: "string"
            - label: "Behance"
              name: "behance"
              widget: "string"
          - label: "Home Page Settings"
            name: "homepage"
            widget: "object"
            fields:
            - label: "Title"
              name: "title"
              widget: "string"
            - label: "Byline"
              name: "byline"
              widget: "string"
          - label: "About Settings"
            name: "about"
            widget: "object"
            fields:
            - label: "Headline"
              name: "headline"
              widget: "string"
            - label: "Text"
              name: "text"
              widget: "string"
          - label: "Contact Settings"
            name: "contact"
            widget: "object"
            fields:
            - label: "Headline"
              name: "headline"
              widget: "string"
            - label: "Link Text"
              name: "link-text"
              widget: "string"
            - label: "Link Url"
              name: "link-url"
              widget: "string"
          - label: "404 Settings"
            name: "four-o-four"
            widget: "object"
            fields:
            - label: "Headline"
              name: "headline"
              widget: "string"
            - label: "Link Text"
              name: "link-text"
              widget: "string"
            - label: "Link Url"
              name: "link-url"
              widget: "string"

  - name: "projects"
    label: "Projects"
    folder: "_projects"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "project"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Category"
        name: "category"
        widget: "string"
      - label: "Role"
        name: "role"
        widget: "string"
      - label: "Direction"
        name: "direction"
        widget: "string"
      - label: "Client"
        name: "client"
        widget: "string"
      - label: "Body"
        name: "body"
        widget: "markdown"